#markdown: redcarpet
highlighter: pygments
paginate: 5
comments: true
# "none" actually means /:categories/:title.html
permalink: none
# author is used lots of places, MUST be JUST name
author: Nate Wiger
# needs to match real URL after redirects from root etc. affects Disqus.
url: http://www.nateware.com
email: natewareblog@gmail.com
title: Nate Wiger in San Diego, CA
subtitle: Musings on software
# http://stackoverflow.com/questions/16422933/how-do-i-use-markdownify-in-jekyll-to-show-an-excerpt-on-the-index
excerpt_separator: <!--more-->
# see footer.html
google_analytics: UA-23188280-1
plugins: [jekyll-paginate]
