markdown: redcarpet
pygments: true
paginate: 5
comments: true
# "none" actually means /:categories/:title.html
permalink: none
# author is used lots of places, MUST be JUST name
author: Nate Wiger
url: http://nateware.com
email: natewareblog@gmail.com
title: Nate Wiger vs Technology
subtitle: Code always works better after a few beers
# http://stackoverflow.com/questions/16422933/how-do-i-use-markdownify-in-jekyll-to-show-an-excerpt-on-the-index
excerpt_separator: <!--more-->
