source 'http://rubygems.org'
gem 'haml'
gem 'sass'
gem 'hpricot'
gem 'pygments.rb'
gem 'jekyll'
# gem 'jekyll-s3', '>=0.0.7'
gem 's3_website'
gem 'jammit'
gem 'jekyll-paginate'
gem 'classifier-reborn'
# gem 'gsl'
